data:
  batch_size: 128
  dataset:
    name: PolSFDataset
    trainpath: $TMPDIR/data
  transform: LogAmplitude, RealImaginary
  img_size: 64
  img_stride: 64
  num_workers: 4
  valid_ratio: 0.15
  test_ratio: 0.15
logging:
  logdir: ./logs
  wandb:
    entity: equivariant_cvnn
    project: polsf
loss:
  name: FocalLoss
  gamma: 3
model:
  activation: ReLU
  channels_ratio: 16
  class: UNet
  res: true
  projection:
    class: NoCtoR
    global: true
    softmax: Softmax
  downsampling: APD_F
  upsampling: APU_F
  latent_dim: Null
  dropout : 0.1
  normalization: 
    method: BatchNorm
    track_running_stats: false
  num_layers: 4
nepochs: 500
optim:
  algo: AdamW
  params:
    lr: 0.001
    weight_decay: 0.005
scheduler:
  algo: StepLR
  params:
    step_size: 1000
    gamma: 1
pretrained: false
world_size: 4
dtype: float64
